% Setup a dielectric FR4 slab simulation
function SetupDoubleRings(type_of_sim, UCDim, lz, R1, w1, R2, w2, eps, kappa,ZMESHRES=40,MESHRES=140);
addpath('../../libraries');
physical_constants;
node = uname.nodename();
% setup the system paths
Paths.SimPath = ['DoubleRings/UCDim_' num2str(UCDim) '/lz_' num2str(lz) '/R1_' num2str(R1) '/R2_' num2str(R2)];
Paths.SimCSX = 'DoubleRings_geometry.xml';
Paths = configureSystemPaths(Paths, node);
addpath([Paths.ResultBasePath 'libraries/']);
Paths.ResultPath = ['Results/SParameters/' Paths.SimPath];
sim_setup.Paths = Paths; 
%-----------------system path setup END---------------------------------------|
sim_setup.Paths = Paths;
sim_setup.FDTD.Write = 'True';
sim_setup.FDTD.numThreads = 4;
sim_setup.FDTD.Run = 'True';
sim_setup.FDTD.fstart = 1e9;
sim_setup.FDTD.fstop = 40e9;
sim_setup.FDTD.EndCriteria = 1e-4;
sim_setup.FDTD.Kinc = [0,0,-1];
sim_setup.FDTD.Polarization = [1,0,0];
sim_setup.FDTD.PML = 'MUR';
sim_setup.Geometry.Show = 'False';
sim_setup.Geometry.grounded = 'True';
if strcmp(type_of_sim,'LEFT') || strcmp(type_of_sim,'RIGHT') || strcmp(type_of_sim,'LEFTRIGHT');
    sim_setup.Geometry.grounded = 'False';
end;
sim_setup.Geometry.MeshResolution = [MESHRES,MESHRES,ZMESHRES];
sim_setup.Geometry.Unit = 1e-3;
sim_setup.Geometry.UCDim = [UCDim, UCDim]; % size of the unit-cell in the xy-plane
SParameters.df = 10e6;
SParameters.fstart = sim_setup.FDTD.fstart;
SParameters.fstop = sim_setup.FDTD.fstop;
SParameters.ResultFilename = ['_w1_' num2str(w1) '_w2_' num2str(w2) '_eps_' num2str(eps) '_kappa_' num2str(kappa) '_' type_of_sim '_lz_' num2str(lz)];
TDDump.Status = 'False';
FDDump.Status = 'False';
PP.DoSPararmeterDump = 'True';
PP.TDDump = TDDump;
PP.FDDump = FDDump;
PP.SParameters = SParameters;
sim_setup.PP = PP;
% Define the materials which are used:
mFR4.Name = 'FR4';
mFR4.Type = 'Material';
mFR4.Properties.Kappa = kappa;
mFR4.Properties.Epsilon = eps;
mCuSheet.Name = 'CuSheet';
mCuSheet.Type = 'ConductingSheet';
mCuSheet.Properties.Thickness = 35e-6;
mCuSheet.Properties.Kappa = 56e6;
materials{1} = mFR4;
materials{2} = mCuSheet;
if strcmp(type_of_sim, 'LEFT');
    lMaterial = mFR4;
    lEpsilon = lMaterial.Properties.Epsilon;
    lKappa = lMaterial.Properties.Kappa;
    sim_setup.PP.lEpsilon = lMaterial.Properties.Epsilon;
    sim_setup.PP.lKappa   = lMaterial.Properties.Kappa;
    sim_setup.Geometry.lMaterial = lMaterial;
elseif strcmp(type_of_sim,'RIGHT');
    rMaterial = mFR4;
    rEpsilon = rMaterial.Properties.Epsilon;
    rKappa = rMaterial.Properties.Kappa;
    sim_setup.PP.rEpsilon = rMaterial.Properties.Epsilon;
    sim_setup.PP.rKappa   = rMaterial.Properties.Kappa;
    sim_setup.Geometry.rMaterial = rMaterial;
elseif strcmp(type_of_sim,'LEFTRIGHT');
    rMaterial = mFR4;
    rEpsilon = rMaterial.Properties.Epsilon;
    rKappa = rMaterial.Properties.Kappa;
    sim_setup.PP.rEpsilon = rMaterial.Properties.Epsilon;
    sim_setup.PP.rKappa   = rMaterial.Properties.Kappa;
    sim_setup.Geometry.rMaterial = rMaterial;
    lMaterial = mFR4;
    lEpsilon = lMaterial.Properties.Epsilon;
    lKappa = lMaterial.Properties.Kappa;
    sim_setup.PP.lEpsilon = lMaterial.Properties.Epsilon;
    sim_setup.PP.lKappa   = lMaterial.Properties.Kappa;
    sim_setup.Geometry.lMaterial = lMaterial;
end;
fc = (sim_setup.FDTD.fstart+sim_setup.FDTD.fstop)/2;
% End of material definition
% Define the objects which are made of the defined materials

oFSS1.Name = 'outer_ring';
oFSS1.MName = 'CuSheet';
oFSS1.Type = 'Polygon';
oFSS1.Thickness = 0;
oFSS1.Center = [0,0];
oFSS1.Prio = 4;
oFR4.Name = 'FR4Substrate';
oFR4.MName = 'FR4';
oFR4.Type = 'Box';
oFR4.Thickness = lz;
oFR4.Bstart = [-UCDim/2, -UCDim/2, 0];
oFR4.Bstop =  [UCDim/2, UCDim/2, oFR4.Thickness];
oFR4.Prio = 1;
Ra = R1;
Ri = R1-w1;
NPoints = 50;
theta = linspace(0,2*pi,NPoints);
Points(1,:) = [Ri*cos(theta(1)), Ra.*cos(theta), Ri.*cos(theta)];
Points(2,:) = [Ri*sin(theta(1)), Ra.*sin(theta), -Ri.*sin(theta)];
oFSS1.Points = Points;

oFSS2 = oFSS1;
oFSS2.Name = 'inner_ring';
NPoints = 50;
Ra = R2;
Ri = R2-w2;
theta = linspace(0,2*pi,NPoints);
Points(1,:) = [Ri*cos(theta(1)), Ra.*cos(theta), Ri.*cos(theta)];
Points(2,:) = [Ri*sin(theta(1)), Ra.*sin(theta), -Ri.*sin(theta)];
oFSS2.Points = Points;

layer1.Name = 'FSS';
layer1.Thickness = 0;
layer1.objects = {oFSS1, oFSS2};
if R1 == 0;
    layer1.objects = {oFSS2};
elseif R2 == 0;
    layer1.objects = {oFSS1};
end;
layer2.Name = 'Substrate';
layer2.Thickness = oFR4.Thickness;
layer2.objects{1} = oFR4;

sim_setup.used_layers = {layer1};
if strcmp(type_of_sim, 'EXACT');
    sim_setup.used_layers = {layer2,layer1};
end;
if lz == 0;
    sim_setup.used_layers = {layer1};
end;

sim_setup.used_materials = materials;
retval = setup_simulation(sim_setup);
end;
