clc;
clear;

kappa = 0.05;
eps = 4.6;
lz = 2;
UCDim = 12;
L = linspace(3, 3.95, 20);
type_of_sim = {"EXACT"};
ZMESHRES = 30;
MESHRES = 200;
w = 0.2;
R = 5;
dTheta = pi/16;
Theta0 = pi/4;
for Theta0 = [0];
    for i = 1:length(type_of_sim);
        SetupDoubleRings(type_of_sim{i}, UCDim, lz, R, w, dTheta, Theta0, eps, kappa,ZMESHRES,MESHRES);
    end;
end;
